### PR TITLE
Try LE Secure connections first before falling back

### LINKED ISSUE #12: Connected but no sound?
Tried the latest pico-asha.uf2 from [GitHub Actions](https://github.com/shermp/Pico-ASHA/actions/runs/10954576807) on a newly bought Pico W with my Oticon More 1 hearing aids.

The Pico W is connected to Windows 11 and Pico-ASHA adapter is selected as the sound output. The LED light is stable, so I guess it means that the hearing aids are connected to the Pico?

Unfortunately, no sound in hearing aids.

### PR DESCRIPTION
**Pull request by shermp**
This PR fixes #12 

It turns out that some hearing aids will allow bonding without LE Secure connections, but then refuse to grant access to the ASHA GATT characteristics.

Pico-ASHA now attempts bonding with LE Secure Connections first, and then disables LE SC as a fallback if it fails.

The prior behavior was the opposite, it upgraded to LE SC if bonding failed.

### CODE REVIEW

**Comment by shermp** [comment]
Sigh... this (or something else I've done) seems to have broken reconnections when moving in/out of range.

Having to manage the whole pairing/bonding process is an absolute PITA :(

**Comment by sk408** [comment]
Is there a command so that we can choose which devices to connect to? One apparent issue that happens is that devices like Resound advertise two different bluetooth addresses. I'm not sure what the difference is but one is named GN and one is  "User's hearing aids". I'll try checking into it myself too

**Comment by shermp** [comment]
Hi @sk408 could you please open a new issue to discuss this? Thank you.

**Comment by shermp** [comment]
Ok, am going to merge this as-is. I have another branch I'm working on that I'm hoping to implement various improvements and fixes.

**Pull request merged**
